[tool.black]
line-length = 88
target-version = ['py310']
skip-string-normalization = false

[tool.ruff]
line-length = 88
exclude = ["build", "dist", ".venv"]
fix = true

[tool.ruff.lint]
select = ["E", "F", "W", "C", "I", "B"]

[tool.pytest.ini_options]
minversion = "8.0"
testpaths = ["tests"]
python_files = "question_*.py"
