name: q3p2
channels:
  - defaults
dependencies:
  tensorflow==2.16.2
  tf-keras==2.16.0
  tensorflow-probability==0.22.1
  choice-learn==1.3.1

  numpy>=1.23,<2.0
  scipy
  pandas
  tqdm

  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - expat=2.7.3=h50f4ffc_4
  - libcxx=20.1.8=hd7fd590_1
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - python=3.11.14=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py311hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - attrs==25.4.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - cloudpickle==3.1.2
      - decorator==5.2.1
      - dm-tree==0.1.9
      - flatbuffers==25.12.19
      - gast==0.7.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - idna==3.11
      - keras==3.13.0
      - libclang==18.1.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - namex==0.1.0
      - numpy==2.4.0
      - opt-einsum==3.4.0
      - optree==0.18.0
      - packaging==25.0
      - pillow==12.0.0
      - protobuf==6.33.2
      - pygments==2.19.2
      - requests==2.32.5
      - rich==14.2.0
      - six==1.17.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - tensorflow-probability==0.25.0
      - termcolor==3.3.0
      - tf-keras==2.20.1
      - typing-extensions==4.15.0
      - urllib3==2.6.2
      - werkzeug==3.1.4
      - wrapt==2.0.1
prefix: /Users/kambam/.conda/envs/q3p2
